services:
  - type: web
    name: unity-school-admin
    env: static
    buildCommand: ./build.sh
    staticPublishPath: build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: NODE_ENV
        value: production
      - key: CI
        value: "false"
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
